In [489]:
import torch

In [490]:
torch.cuda.is_available()

True

In [491]:
torch.cuda.device_count()

1

In [492]:
torch.cuda.current_device()

0

In [493]:
torch.cuda.device(0)

In [494]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 4060 Ti'

# Tensor

### Create a Tensor

In [495]:
# create an empty tensor of size d
d = 3
x = torch.empty(d, dtype=torch.int)

x.dtype

torch.int32

In [496]:
# m x n matrix
m, n = 3, 2
x = torch.empty(m, n)

x

tensor([[1.4153e-43, 1.6255e-43],
        [1.3312e-43, 1.4013e-43],
        [1.4153e-43, 1.6535e-43]])

In [497]:
torch.empty(3, 4, 5)

tensor([[[1.0320e+05, 0.0000e+00, 0.0000e+00, 0.0000e+00, 5.1824e+01],
         [1.6090e+19, 2.1302e-04, 5.4410e-05, 1.2769e+19, 8.9288e+02],
         [4.6173e+24, 7.1843e+22, 1.2090e+33, 4.1208e+21, 6.6822e-07],
         [1.3542e-05, 4.2488e-05, 1.2090e+33, 2.8397e+29, 1.8694e+25]],

        [[1.3237e+22, 1.8106e+22, 6.9470e+22, 1.1095e+27, 3.3076e+21],
         [1.8451e+05, 3.6868e+03, 5.4319e-08, 5.4319e-08, 5.4319e-08],
         [3.3949e-09, 3.3949e-09, 3.3949e-09, 1.0003e+33, 1.2999e-08],
         [1.7740e+28, 4.3063e+21, 2.7489e+26, 6.2687e+22, 4.7428e+30]],

        [[6.7113e+22, 4.7428e+30, 1.5297e+19, 2.9028e+03, 3.2498e-09],
         [2.7067e+23, 7.4937e+31, 4.1653e+12, 7.3961e+31, 3.7323e+03],
         [7.8718e-07, 3.1484e-06, 8.8401e-07, 1.3282e+19, 8.4727e+11],
         [8.9495e+11, 1.7633e+25, 1.7636e+25, 9.6805e-39, 9.7025e+24]]])

In [498]:
# tensor of random values
torch.rand(2, 2)

tensor([[0.0248, 0.9119],
        [0.6825, 0.7371]])

In [499]:
# np flavour
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [500]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4729, 0.0562, 0.2247],
        [0.7994, 0.7645, 0.1479]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [501]:
x = torch.tensor([2.4, 9.9])

x

tensor([2.4000, 9.9000])

### Attributes of Tensor

In [502]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Basic Operations
https://docs.pytorch.org/docs/stable/torch.html

### Arithmitic Operations

In [503]:
x, y = torch.tensor([[1, 2], [3, 4]]), torch.tensor([[5, 6], [7, 8]])

#### Addition

In [504]:
x + y

tensor([[ 6,  8],
        [10, 12]])

In [505]:
torch.add(x, y)

tensor([[ 6,  8],
        [10, 12]])

Every function with underscore "_" will do an in-place operation

In [506]:
# this will modify y, add all elements of x to y
y.add_(x)

y

tensor([[ 6,  8],
        [10, 12]])

#### Multiplication (Elementwise)

In [507]:
x, y = torch.tensor([[1, 2], [3, 4]]), torch.tensor([[5, 6], [7, 8]])

In [508]:
x * y

tensor([[ 5, 12],
        [21, 32]])

In [509]:
torch.mul(x, y)

tensor([[ 5, 12],
        [21, 32]])

#### Slicing Operation

In [510]:
x = torch.rand(3, 5)

In [511]:
x

tensor([[0.1320, 0.2058, 0.3805, 0.8441, 0.0337],
        [0.5479, 0.2155, 0.4261, 0.0498, 0.3540],
        [0.9712, 0.9268, 0.6314, 0.0895, 0.4565]])

In [512]:
x[:, 0] # first column of all rows

tensor([0.1320, 0.5479, 0.9712])

In [513]:
x[1, :] # second row of all columns

tensor([0.5479, 0.2155, 0.4261, 0.0498, 0.3540])

In [514]:
# x[:, -1] # last column of all rows
x[..., -1] # last column of all rows

tensor([0.0337, 0.3540, 0.4565])

In [515]:
x[:,1] = 0
print(x)

tensor([[0.1320, 0.0000, 0.3805, 0.8441, 0.0337],
        [0.5479, 0.0000, 0.4261, 0.0498, 0.3540],
        [0.9712, 0.0000, 0.6314, 0.0895, 0.4565]])


Each of these operations can be run on the CPU and Accelerator such as CUDA, MPS, MTIA, or XPU.

By default, tensors are created on the CPU $\to$ explicitly move tensors to the accelerator using `.to` method (after checking for accelerator availability). 

Copying large tensors across devices can be expensive in terms of time and memory!

In [516]:
torch.accelerator.is_available()

True

In [517]:
# move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

### Accelerators
https://docs.pytorch.org/docs/stable/torch.html#accelerators

### Joining Tensors

In [518]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6]])


#### Single-element tensors 

one-element tensor, for example by aggregating all values of a tensor into one value $\to$ can convert it to a Python numerical value using `item()`

In [519]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

21 <class 'int'>


# Autograd
Built-in engine that supports automatic computation of gradient for any computational graph

In [520]:
x = torch.randn(3, requires_grad=True)
x

tensor([ 0.5694, -0.7457,  1.6023], requires_grad=True)

In [521]:
y = x + 2
y

tensor([2.5694, 1.2543, 3.6023], grad_fn=<AddBackward0>)

In [522]:
z = y * y * 2
z

tensor([13.2035,  3.1463, 25.9532], grad_fn=<MulBackward0>)

In [523]:
z = z.mean()
z

tensor(14.1010, grad_fn=<MeanBackward0>)

In [524]:
z.backward() # dz/dx
x.grad

tensor([3.4259, 1.6723, 4.8031])