In [56]:
import torch

In [57]:
torch.cuda.is_available()

True

In [58]:
torch.cuda.device_count()

1

In [59]:
torch.cuda.current_device()

0

In [60]:
torch.cuda.device(0)

In [61]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 5070'

# Tensor

### Create a Tensor

In [62]:
# create an empty tensor of size d
d = 3
x = torch.empty(d, dtype=torch.int)

x.dtype

torch.int32

In [63]:
# m x n matrix
m, n = 3, 2
x = torch.empty(m, n)

x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [64]:
torch.empty(3, 4, 5)

tensor([[[2.3783e+18, 8.6040e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])

In [65]:
# tensor of random values
torch.rand(2, 2)

tensor([[0.5015, 0.3065],
        [0.7728, 0.5282]])

In [66]:
# np flavour
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [80]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0243, 0.3449, 0.9794],
        [0.5026, 0.1143, 0.6363]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [67]:
x = torch.tensor([2.4, 9.9])

x

tensor([2.4000, 9.9000])

### Attributes of Tensor

In [81]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Basic Operations
https://docs.pytorch.org/docs/stable/torch.html

### Arithmitic Operations

In [82]:
x, y = torch.tensor([[1, 2], [3, 4]]), torch.tensor([[5, 6], [7, 8]])

#### Addition

In [83]:
x + y

tensor([[ 6,  8],
        [10, 12]])

In [84]:
torch.add(x, y)

tensor([[ 6,  8],
        [10, 12]])

Every function with underscore "_" will do an in-place operation

In [85]:
# this will modify y, add all elements of x to y
y.add_(x)

y

tensor([[ 6,  8],
        [10, 12]])

#### Multiplication (Elementwise)

In [86]:
x, y = torch.tensor([[1, 2], [3, 4]]), torch.tensor([[5, 6], [7, 8]])

In [87]:
x * y

tensor([[ 5, 12],
        [21, 32]])

In [88]:
torch.mul(x, y)

tensor([[ 5, 12],
        [21, 32]])

#### Slicing Operation

In [89]:
x = torch.rand(3, 5)

In [90]:
x

tensor([[0.0922, 0.0311, 0.9018, 0.4772, 0.4268],
        [0.0388, 0.4116, 0.3554, 0.8839, 0.0062],
        [0.6418, 0.5113, 0.9177, 0.5883, 0.8483]])

In [91]:
x[:, 0] # first column of all rows

tensor([0.0922, 0.0388, 0.6418])

In [92]:
x[1, :] # second row of all columns

tensor([0.0388, 0.4116, 0.3554, 0.8839, 0.0062])

In [100]:
# x[:, -1] # last column of all rows
x[..., -1] # last column of all rows

tensor([0.4268, 0.0062, 0.8483])

In [101]:
x[:,1] = 0
print(x)

tensor([[0.0922, 0.0000, 0.9018, 0.4772, 0.4268],
        [0.0388, 0.0000, 0.3554, 0.8839, 0.0062],
        [0.6418, 0.0000, 0.9177, 0.5883, 0.8483]])


Each of these operations can be run on the CPU and Accelerator such as CUDA, MPS, MTIA, or XPU.

By default, tensors are created on the CPU $\to$ explicitly move tensors to the accelerator using `.to` method (after checking for accelerator availability). 

Copying large tensors across devices can be expensive in terms of time and memory!

In [94]:
torch.accelerator.is_available()

True

In [96]:
# move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

### Accelerators
https://docs.pytorch.org/docs/stable/torch.html#accelerators

### Joining Tensors

In [102]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6]])


#### Single-element tensors 

one-element tensor, for example by aggregating all values of a tensor into one value $\to$ can convert it to a Python numerical value using `item()`

In [103]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

21 <class 'int'>
