In [92]:
import torch

In [93]:
torch.cuda.is_available()

True

In [94]:
torch.cuda.device_count()

1

In [95]:
torch.cuda.current_device()

0

In [96]:
torch.cuda.device(0)

In [97]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 4060 Ti'

# Tensor

### Create a Tensor

In [98]:
# create an empty tensor of size d
d = 3
x = torch.empty(d, dtype=torch.int)

x.dtype

torch.int32

In [99]:
# m x n matrix
m, n = 3, 2
x = torch.empty(m, n)

x

tensor([[4.5051e+30, 1.8469e+25],
        [1.7343e+02, 7.2143e+22],
        [2.9799e+12, 8.7524e-04]])

In [100]:
torch.empty(3, 4, 5)

tensor([[[2.2529e-22, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 2.2498e-22, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.2499e-22],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[2.2499e-22, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.2498e-22],
         [0.0000e+00, 2.2498e-22, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [2.2498e-22, 0.0000e+00, 2.2498e-22, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 2.2499e-22, 0.0000e+00, 1.4013e-45, 0.0000e+00]],

        [[2.2499e-22, 0.0000e+00, 2.2503e-22, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 2.2499e-22, 0.0000e+00, 2.2500e-22, 0.0000e+00],
         [3.3631e-44, 0.0000e+00, 1.2537e-38, 0.0000e+00, 1.4013e-45],
         [0.0000e+00, 1.5891e-42, 0.0000e+00, 2.3822e-44, 1.6816e-44]]])

In [101]:
# tensor of random values
torch.rand(2, 2)

tensor([[0.6872, 0.6869],
        [0.0337, 0.8107]])

In [102]:
# np flavour
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [103]:
x = torch.tensor([2.4, 9.9])

x

tensor([2.4000, 9.9000])

### Basic Operations

In [104]:
x, y = torch.rand(2, 2), torch.rand(2, 2)

In [105]:
x

tensor([[0.7092, 0.2782],
        [0.9995, 0.1809]])

In [106]:
y

tensor([[0.8509, 0.7073],
        [0.1222, 0.9117]])

#### Addition

In [ ]:
x + y

tensor([[1.5601, 0.9855],
        [1.1217, 1.0926]])

In [ ]:
torch.add(x, y)

tensor([[1.5601, 0.9855],
        [1.1217, 1.0926]])

Every function with underscore "_" will do an in-place operation

In [ ]:
# this will modify y, add all elements of x to y
y.add_(x)

y

tensor([[1.5601, 0.9855],
        [1.1217, 1.0926]])